select
ude.EMPLID,
ude.EMPLOYEE_NBR,
ude.USERNAME,
ude.LAST_NAME,
ude.FIRST_NAME,
ude.EMAIL_ADDRESS,
udd.DEPARTMENT_CD,
udd.DEPARTMENT_DESCR,
urc.RESPONSIBILITY_CENTER_CD,
urc.RESPONSIBILITY_CENTER_DESCR

from UD_DATA.PY_EMPLOYMENT pye
join UD_DATA.UD_EMPLOYEE ude on pye.EMPLOYEE_KEY = ude.EMPLOYEE_KEY
join UD_DATA.UD_EMPLOYEE_FULL_PART_TIME efpt on pye.EMPLOYEE_FULL_PART_TIME_KEY = efpt.EMPLOYEE_FULL_PART_TIME_KEY
join UD_DATA.UD_ASSIGNMENT_STATUS uas on pye.ASSIGNMENT_STATUS_KEY = uas.ASSIGNMENT_STATUS_KEY
join UD_DATA.UD_DEPARTMENT udd on pye.DEPARTMENT_KEY = udd.DEPARTMENT_KEY
join UD_DATA.UD_RESPONSIBILITY_CENTER urc on udd.RESPONSIBILITY_CENTER_CD = urc.RESPONSIBILITY_CENTER_CD
join UD_DATA.UD_JOB udj on pye.JOB_KEY = udj.JOB_KEY
join UD_DATA.UD_CALENDAR cal on pye.CALENDAR_KEY = cal.CALENDAR_KEY

where cal.CALENDAR_KEY = SYS_CONTEXT ('G$CONTEXT', 'PYM_CU_CAL_K_0000')
and udd.current_flg = 1 and udj.current_flg = 1 and urc.current_flg = 1
and udj.JOB_TYPE in ('Academic', 'Faculty', 'Post Doctoral')